/**
 * Real portfolio data from Muhamad Reza Muktasib's CV
 * Supabase will override these when connected.
 */

export const FALLBACK_PROFILE = {
  name: 'Muhamad Reza Muktasib',
  short_name: 'Reza',
  tagline: 'Fullstack Engineer · Software Engineer',
  bio: "Experienced Fullstack Engineer building and maintaining scalable web applications using JavaScript, Python, PHP, Go, Java, Laravel, and Next.js. Proven in cloud (AWS, GCP) and Docker deployments along with CI/CD pipeline implementation. I create responsive UI/UX from Figma designs and apply Agile Development and Product Owner principles for effective, goal-aligned project delivery.",
  avatar_url: 'https://media-cgk1-2.cdn.whatsapp.net/v/t61.24694-24/473401235_1552986355362901_3748418445986158654_n.jpg?ccb=11-4&oh=01_Q5Aa4gGY_VqTRJU_lNLE9ORCio6yq-3fwA3MpEfi1gdqDJvdVw&oe=6A0E9538&_nc_sid=5e03e0&_nc_cat=105',
  email: 'reza.muktasib@gmail.com',
  github_url: 'https://github.com/reza1290',
  linkedin_url: 'https://linkedin.com/in/m-rezamuktasib',
  location: 'Indonesia 🇮🇩',
  toeic: '840',
}

export const FALLBACK_SKILLS = [
  // Languages
  { id: 'l1', name: 'JavaScript', category: 'language', proficiency: 95, sort_order: 1 },
  { id: 'l2', name: 'TypeScript', category: 'language', proficiency: 85, sort_order: 2 },
  { id: 'l3', name: 'PHP', category: 'language', proficiency: 88, sort_order: 3 },
  { id: 'l4', name: 'Python', category: 'language', proficiency: 78, sort_order: 4 },
  { id: 'l5', name: 'Go (Golang)', category: 'language', proficiency: 72, sort_order: 5 },
  { id: 'l6', name: 'Java', category: 'language', proficiency: 75, sort_order: 6 },
  { id: 'l7', name: 'C (STM32)', category: 'language', proficiency: 65, sort_order: 7 },

  // Frameworks
  { id: 'f1', name: 'React', category: 'framework', proficiency: 92, sort_order: 8 },
  { id: 'f2', name: 'Next.js', category: 'framework', proficiency: 90, sort_order: 9 },
  { id: 'f3', name: 'Laravel', category: 'framework', proficiency: 90, sort_order: 10 },
  { id: 'f4', name: 'Node.js', category: 'framework', proficiency: 87, sort_order: 11 },
  { id: 'f5', name: 'Flutter', category: 'framework', proficiency: 78, sort_order: 12 },
  { id: 'f6', name: 'Remix', category: 'framework', proficiency: 72, sort_order: 13 },
  { id: 'f7', name: 'GraphQL', category: 'framework', proficiency: 70, sort_order: 14 },

  // Infrastructure & Tools
  { id: 't1', name: 'Docker', category: 'tool', proficiency: 85, sort_order: 15 },
  { id: 't2', name: 'AWS', category: 'tool', proficiency: 80, sort_order: 16 },
  { id: 't3', name: 'GCP', category: 'tool', proficiency: 72, sort_order: 17 },
  { id: 't4', name: 'PostgreSQL', category: 'tool', proficiency: 85, sort_order: 18 },
  { id: 't5', name: 'MongoDB', category: 'tool', proficiency: 82, sort_order: 19 },
  { id: 't6', name: 'Firebase', category: 'tool', proficiency: 78, sort_order: 20 },
  { id: 't7', name: 'CI/CD', category: 'tool', proficiency: 83, sort_order: 21 },
  { id: 't8', name: 'WebRTC', category: 'tool', proficiency: 75, sort_order: 22 },
]

export const FALLBACK_JOURNEY = [
  {
    id: 'j1',
    title: 'Associate Degree · PENS',
    description: 'Enrolled in Informatics Engineering at Politeknik Elektronika Negeri Surabaya. Graduated with a GPA of 3.94/4.00 — top of class.',
    year: 2022,
    end_year: 2025,
    type: 'education',
    sort_order: 1,
  },
  {
    id: 'j2',
    title: 'Freelance Web Developer · Cipta Kode',
    description: 'Completed 10+ freelance projects using React, Laravel, Python, and AI technologies — delivering tailored web solutions for diverse client needs.',
    year: 2022,
    end_year: null,
    type: 'work',
    sort_order: 2,
  },
  {
    id: 'j3',
    title: 'Web Developer · PT. Digital Solusi Master',
    description: 'Maintained Diakademik, used by 2,000+ students. Converted Figma designs to Tailwind CSS interfaces achieving 95% user satisfaction score.',
    year: 2023,
    end_year: 2024,
    type: 'work',
    sort_order: 3,
  },
  {
    id: 'j4',
    title: 'Product Owner & Flutter Dev · BudgetIn App',
    description: 'Led a 5-person team using Agile methodologies to develop and launch the BudgetIn App — now on the Play Store with a 4.8+ star rating.',
    year: 2024,
    end_year: 2024,
    type: 'milestone',
    sort_order: 4,
  },
  {
    id: 'j5',
    title: 'Backend + DevOps · Pens MyToefl App',
    description: 'Built a Duolingo-style TOEFL quiz app with a 9-person team. Achieved 50ms average response time using Laravel + MongoDB + Docker microservices.',
    year: 2024,
    end_year: 2024,
    type: 'work',
    sort_order: 5,
  },
  {
    id: 'j6',
    title: 'IISMA Scholar · Hanyang University',
    description: 'Awarded the prestigious IISMA scholarship for a student exchange at Hanyang University, South Korea. Achieved 93.3/100 GPA.',
    year: 2024,
    end_year: 2025,
    type: 'education',
    sort_order: 6,
  },
  {
    id: 'j7',
    title: 'Marketing & Growth · ZEP Co., Ltd',
    description: "Grew ZEP Indonesia's social media to 3,000+ followers in 2 months. Built automation scripts reducing manual reporting time by 80%.",
    year: 2024,
    end_year: 2025,
    type: 'work',
    sort_order: 7,
  },
  {
    id: 'j8',
    title: 'Backend & DevOps · Mutio App',
    description: 'Maintained the Mutio App serving 4,100 daily active users. Optimized API performance and database queries on AWS infrastructure.',
    year: 2025,
    end_year: null,
    type: 'work',
    sort_order: 8,
  },
  {
    id: 'j9',
    title: 'Fullstack Engineer · Exzam.id',
    description: 'Built a multi-tenant online exam platform used by teachers and lecturers. Achieved stable performance for 120+ concurrent users.',
    year: 2025,
    end_year: 2025,
    type: 'milestone',
    sort_order: 9,
  },
  {
    id: 'j10',
    title: 'Backend Engineer · PT Paragon × Sobat Kreasi',
    description: 'Migrated Batch Management across 24+ active warehouses for a large enterprise WMS. Built SAP integration modules for real-time synchronization.',
    year: 2025,
    end_year: null,
    type: 'work',
    sort_order: 10,
  },
]

export const FALLBACK_PROJECTS = [
  {
    id: 'p1',
    title: 'Procspy',
    subtitle: 'Open-Source Anti-Cheating Proctoring System',
    description: 'Procspy is an open-source automated proctoring application designed to uphold academic integrity during online assessments. Built as my final university graduation project at PENS.',
    long_description: 'Procspy is a full-featured anti-cheating proctoring platform that combines a Chrome Extension, WebRTC server, and a Next.js dashboard to enable real-time monitoring during online exams. The system handles 30 concurrent users with only 20% CPU usage on a dual-core CPU — a benchmark I am particularly proud of.',
    highlights: [
      'Handles 30 concurrent users with only 20% CPU usage on dual-core hardware',
      'Built with TypeScript + Express using Hexagonal Architecture for maintainability',
      'WebRTC server using WebSockets + Mediasoup for real-time media streaming',
      'Custom socket protocol for secure Chrome Extension ↔ Next.js dashboard communication',
      'Open-sourced the WebRTC component as a Chrome Extension',
      'Integrated as the proctoring engine for Exzam.id',
    ],
    image_url: null,
    tech_stack: ['TypeScript', 'Next.js', 'MongoDB', 'WebRTC', 'Mediasoup', 'WebSockets', 'Chrome Extension', 'Express'],
    demo_url: 'https://docs.procspy.link',
    repo_url: 'https://github.com/reza1290',
    featured: true,
    sort_order: 1,
    gradient: 'linear-gradient(135deg, #1a0a3d, #4a1fa8)',
    period: 'Jun 2024 – Present',
    role: 'Fullstack Engineer (Lead)',
  },
  {
    id: 'p2',
    title: 'Exzam.id',
    subtitle: 'Multi-Tenant Online Examination Platform',
    description: 'A multi-tenant online examination platform used by elementary school teachers and university lecturers to conduct secure digital exams with automated proctoring.',
    long_description: 'Exzam.id is a production SaaS product serving both school teachers and university lecturers. I built the entire frontend using React with a custom internal UI component library, and the backend with Laravel managing multi-tenant workflows. Integrated Procspy as the proctoring engine and Midtrans for payments.',
    highlights: [
      'Multi-tenant architecture supporting both schools and universities',
      'Custom internal UI component library — reduced development time by 40%',
      'Stable performance for 120+ concurrent exam users',
      'Automated proctoring via Procspy integration',
      'Midtrans payment gateway for subscriptions and institutional licensing',
      'Subscription-based access with feature gating logic',
    ],
    image_url: null,
    tech_stack: ['React', 'Laravel', 'PHP', 'MySQL', 'Midtrans', 'Procspy', 'Tailwind CSS'],
    demo_url: 'https://exzam.id',
    repo_url: 'https://github.com/reza1290',
    featured: true,
    sort_order: 2,
    gradient: 'linear-gradient(135deg, #0a2a1a, #1a7a4a)',
    period: 'Jun 2025 – Aug 2025',
    role: 'Fullstack Engineer',
  },
  {
    id: 'p3',
    title: 'CV Evaluator',
    subtitle: 'AI-Powered Resume Analysis with Semantic Search',
    description: 'An AI-powered CV evaluation application leveraging Next.js, OpenAI, LangChain, and Pinecone vector search to provide intelligent resume insights and job matching.',
    long_description: 'I engineered this AI-powered tool to evaluate CVs using advanced language models. The system uses Pinecone for semantic search, OpenAI + LangChain for NLP processing, AWS S3 for file storage, and NeonDB with DrizzleORM as the database layer — all orchestrated in a clean Next.js full-stack architecture.',
    highlights: [
      'Semantic search using Pinecone vector database for highly relevant insights',
      'OpenAI + LangChain for advanced NLP and CV analysis',
      'AWS S3 for secure file storage and management',
      'NeonDB (serverless Postgres) + DrizzleORM as the data layer',
      'Real-time feedback on CV quality and job matching scores',
    ],
    image_url: null,
    tech_stack: ['Next.js', 'OpenAI', 'LangChain', 'Pinecone', 'AWS S3', 'NeonDB', 'DrizzleORM', 'TypeScript'],
    demo_url: null,
    repo_url: 'https://github.com/reza1290',
    featured: true,
    sort_order: 3,
    gradient: 'linear-gradient(135deg, #1a1500, #7a5a00)',
    period: 'Apr 2025 – May 2025',
    role: 'Fullstack Engineer',
  },
  {
    id: 'p4',
    title: 'BudgetIn App',
    subtitle: 'Personal Finance App — Play Store 4.8★',
    description: 'A personal budget management app built with Flutter, now live on the Play Store with a 4.8+ star rating. Led a 5-person team using Agile methodologies.',
    long_description: 'As both Product Owner and lead Flutter developer, I managed the full development lifecycle of BudgetIn — from requirement gathering to Play Store deployment. I applied Scrum methodologies to ensure efficient sprint delivery and stakeholder alignment throughout.',
    highlights: [
      '4.8+ star rating on Google Play Store',
      'Led a 5-person team as Product Owner',
      'Full Agile/Scrum implementation across the development lifecycle',
      'Built intuitive Flutter UI with responsive layouts',
      'Successfully deployed to Play Store within the project timeline',
    ],
    image_url: null,
    tech_stack: ['Flutter', 'Dart', 'Firebase', 'Agile/Scrum'],
    demo_url: null,
    repo_url: 'https://github.com/reza1290',
    featured: false,
    sort_order: 4,
    gradient: 'linear-gradient(135deg, #1a0d2a, #6a1a9a)',
    period: 'Mar 2024 – Jun 2024',
    role: 'Product Owner & Flutter Developer',
  },
  {
    id: 'p5',
    title: 'Pens MyToefl App',
    subtitle: 'Duolingo-Style TOEFL Quiz Platform',
    description: 'A collaborative TOEFL preparation app built with a 9-person team. Features Duolingo-style leveling gameplay with a 50ms average API response time.',
    long_description: 'I contributed as Backend Engineer, DevOps, and Flutter developer on this 9-person team project. The app replicates the gamified Duolingo experience for TOEFL preparation, complete with scoring, authentication, and Docker-deployed microservices on DigitalOcean.',
    highlights: [
      '50ms average API response time after optimization',
      'Microservices architecture with Docker on DigitalOcean',
      'CI/CD pipelines automating testing and deployment',
      'Laravel backend for quiz service with auth + score processing',
      'MongoDB for efficient TOEFL data storage and retrieval',
      'Flutter UI with Duolingo-style leveling game mechanics',
    ],
    image_url: null,
    tech_stack: ['Laravel', 'Flutter', 'MongoDB', 'Docker', 'DigitalOcean', 'CI/CD'],
    demo_url: null,
    repo_url: 'https://github.com/reza1290',
    featured: false,
    sort_order: 5,
    gradient: 'linear-gradient(135deg, #001a2a, #006699)',
    period: 'Apr 2024 – Jun 2024',
    role: 'Backend Engineer & Flutter Developer',
  },
  {
    id: 'p6',
    title: 'Warehouse Management System',
    subtitle: 'Enterprise WMS for PT Paragon — 24+ Warehouses',
    description: 'Contributed to a large-scale enterprise WMS integrated with an ERP ecosystem for PT Paragon Technology. Migrated Batch Management across 24+ active warehouses.',
    long_description: 'This is one of the most impactful projects I worked on — a large enterprise Warehouse Management System handling tens of thousands of monthly transactions across 24+ warehouses. I built the SAP integration modules for real-time synchronization and led the Batch Management migration.',
    highlights: [
      'Batch Management migration across 24+ active warehouses',
      'SAP integration modules for real-time data synchronization',
      'Improved traceability and inventory accuracy across all locations',
      'High reliability system for tens of thousands of monthly transactions',
      'Cross-functional collaboration with enterprise stakeholders',
    ],
    image_url: null,
    tech_stack: ['Java', 'SAP Integration', 'Enterprise WMS', 'PostgreSQL'],
    demo_url: null,
    repo_url: null,
    featured: false,
    sort_order: 6,
    gradient: 'linear-gradient(135deg, #1a0a0a, #7a2020)',
    period: 'Aug 2025 – Present',
    role: 'Backend Engineer & DevOps',
  },
]

export const FALLBACK_AWARDS = [
  { id: 'a1', title: 'IISMA Awardee 2024', org: 'Hanyang University, South Korea', year: 2024, icon: '🏆' },
  { id: 'a2', title: 'Silver Medal — IYSAA, WSEEC', org: 'International Competition', year: 2023, icon: '🥈' },
  { id: 'a3', title: '1st Place — Business Plan', org: 'Fasilkomfest 2023 · UPN Jawa Timur', year: 2023, icon: '🥇' },
  { id: 'a4', title: '2nd Place — IE FAIR 17th', org: 'ITS · Business Plan Competition', year: 2023, icon: '🥈' },
  { id: 'a5', title: '3rd Place — UI/UX Competition', org: 'Fasilkomfest 2023 · UPN Jawa Timur', year: 2023, icon: '🥉' },
  { id: 'a6', title: '3rd Place — Cerdas Cermat', org: 'SMA Awards · Jawa Pos', year: 2023, icon: '🥉' },
]

export const FALLBACK_CERTIFICATIONS = [
  { id: 'c1', name: 'Next.js (JS/TS) Course', issuer: 'Udemy', year: 2025 },
  { id: 'c2', name: 'Golang Course', issuer: 'Udemy', year: 2025 },
  { id: 'c3', name: 'Docker & Kubernetes', issuer: 'Udemy', year: 2025 },
  { id: 'c4', name: 'Junior Web Developer', issuer: 'BNSP', year: 2023 },
  { id: 'c5', name: 'JavaScript Fundamental', issuer: 'Dicoding', year: 2023 },
  { id: 'c6', name: 'SQL Fundamental', issuer: 'Dicoding', year: 2023 },
  { id: 'c7', name: 'Project Management', issuer: 'Dicoding', year: 2023 },
  { id: 'c8', name: 'Programming Basic with C', issuer: 'Dicoding', year: 2023 },
]
